name: Sync Data After Merge

permissions:
  contents: read

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  sync-data:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Log event info
        run: |
          echo "🔁 Pull request #${{ github.event.pull_request.number }} was merged into main."
          echo "📦 Commit SHA: ${{ github.event.pull_request.merge_commit_sha }}"
          echo "👤 Merged by: ${{ github.event.pull_request.merged_by.login }}"

      - name: Send GET request to sync data endpoint (with retry)
        run: |
          echo "🚀 Attempting sync..."

          max_retries=3
          count=1
          success=0

          while [ $count -le $max_retries ]; do
            echo "🔁 Attempt $count..."

            response=$(curl -s -L -w "\nHTTP_STATUS_CODE:%{http_code}" -X GET https://www.themontessorians.xyz/api/cron/sync-data -H "Authorization: Bearer ${{ secrets.SYNC_TOKEN }}")

            body=$(echo "$response" | sed '$d')
            status=$(echo "$response" | tail -n1 | cut -d':' -f2)

            echo "📨 Response Body:"
            echo "$body"
            echo "✅ Status Code: $status"

            if [ "$status" -eq 200 ]; then
              echo "✅ Sync succeeded on attempt $count"
              success=1
              break
            else
              echo "⚠️ Sync failed with status $status"
              count=$((count + 1))
              sleep 5
            fi
          done

          if [ "$success" -ne 1 ]; then
            echo "❌ All $max_retries sync attempts failed."
            exit 1
          fi
