name: Validate YAML Schema

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate profile schemas
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install AJV CLI
        run: npm install -g ajv-cli

      - name: Validate YAML against JSON Schema
        run: |
          for file in profiles/*.yaml; do
            echo "Validating $file"
            ajv validate -s profile.schema.json -d "$file" --yaml --strict=false
          done