name: Validate YAML Schema

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate profile schemas
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install YAML schema validator
        run: pip install yamale

      - name: Validate profile files
        run: |
          for file in profiles/*.yaml; do
            echo "Validating $file"
            yamale -s profile.schema.json "$file"
          done