name: Validate Profiles

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate schema + image existence
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install ajv-cli js-yaml

      - name: Validate YAML against JSON Schema
        run: |
          for file in data/*.yaml; do
            echo "Validating schema for $file"
            json=$(npx -y js-yaml "$file")
            echo "$json" > temp.json
            npx ajv-cli validate -s profile.schema.json -d temp.json --strict=false
          done

      - name: Check for missing or invalid image formats
        run: |
          for file in data/*.yaml; do
            slug=$(basename "$file" .yaml)
            valid_image="images/${slug}.jpg"
            jpeg_image="images/${slug}.jpeg"
            png_image="images/${slug}.png"

            if [ -f "$jpeg_image" ] || [ -f "$png_image" ]; then
              echo "❌ Invalid image format for $slug. Use .jpg instead of .jpeg or .png"
              exit 1
            fi

            if [ ! -f "$valid_image" ]; then
              echo "❌ Missing required image: $valid_image"
              exit 1
            else
              echo "✅ Valid .jpg image found for $slug"  
            fi
          done
